[build]
  publish = "."
  functions = "netlify/functions"

[build.environment]
  NODE_VERSION = "18"
  RESEND_API_KEY = "re_WHQSU4PM_Cng9WwAVC34wctom1avMf87P"
  RESEND_AUDIENCE_ID = "938531ce-4872-4327-973f-7bb67013ca89"

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

[[headers]]
  for = "/subscribe"
  [headers.values]
    X-Robots-Tag = "noindex"

[[redirects]]
  from = "/subscribe"
  to = "/subscribe.html"
  status = 200
