backend:
  name: github
  repo: ruicastilho23/OBrasileiro
  branch: main


media_folder: "static/uploads"     # where uploaded images are saved in repo
public_folder: "/static/uploads"   # how they are referenced on the site

collections:
  - name: "home"
    label: "Homepage"
    files:
      - label: "Homepage Content"
        name: "home"
        file: "content/home.json"
        fields:
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Subtitle", name: "subtitle", widget: "string" }
          - { label: "Description", name: "description", widget: "text" }
          - { label: "Hero Image", name: "hero_image", widget: "image" }

  - name: "menu"
    label: "Menu"
    files:
      - label: "Menu Items"
        name: "menu"
        file: "content/menu.json"
        fields:
          - label: "Items"
            name: "items"
            widget: "list"
            fields:
              - { label: "Name", name: "name", widget: "string" }
              - { label: "Description", name: "description", widget: "text" }
              - { label: "Price", name: "price", widget: "string" }
              - { label: "Photo", name: "photo", widget: "image" }
